server:
  port: 18082
  
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: RABBITMQ-QUICKSTART-PROVIDER
  rabbitmq:
    host: ****
    virtual-host: /****
    port: 32002
    username: ****
    password: ****
    publisher-confirms: true

eureka:
  client:
    enabled: false    
    
eos:
  application:
    sys-code: CCMS
    sys-key: 0176c8bde0b14ca0ae769454187c9b38
 